/**
 * One turn of the conversation.
 *
 * Answer text is segmented so `[1]` becomes a clickable chip. Chips resolve
 * against `citations` once the stream has finished, and against `sources`
 * before then — the backend sends every supplied source up front precisely so a
 * marker is clickable the instant it is typed rather than only at the end.
 */

import { segmentAnswer } from '../lib/citations'
import type { ChatMessage, Citation } from '../types'

import { CitationChip } from './CitationChip'

interface Props {
  message: ChatMessage
  activeChunkId: string | null
  onSelectCitation: (citation: Citation) => void
}

export function MessageBubble({ message, activeChunkId, onSelectCitation }: Props) {
  if (message.role === 'user') {
    return (
      <article className="turn turn-user">
        <p className="turn-text">{message.content}</p>
      </article>
    )
  }

  // Prefer the narrowed set; fall back to everything supplied while streaming.
  const resolvable = message.citations.length > 0 ? message.citations : message.sources
  const segments = segmentAnswer(message.content, resolvable)
  const showCursor = message.streaming
  const waiting = message.streaming && message.content.length === 0

  return (
    <article className="turn turn-assistant">
      {waiting ? (
        <p className="turn-waiting" aria-live="polite">
          <span className="dot" />
          <span className="dot" />
          <span className="dot" />
          <span className="visually-hidden">Searching the documents…</span>
        </p>
      ) : (
        <p className="turn-text">
          {segments.map((segment, index) =>
            segment.kind === 'text' ? (
              <span key={index}>{segment.text}</span>
            ) : (
              <CitationChip
                key={index}
                citation={segment.citation}
                marker={segment.marker}
                active={activeChunkId === segment.citation.chunk_id}
                onSelect={onSelectCitation}
              />
            ),
          )}
          {showCursor && <span className="caret" aria-hidden="true" />}
        </p>
      )}

      {message.error && (
        <p className="turn-error" role="alert">
          <strong>{message.error.title}.</strong> {message.error.detail}
        </p>
      )}

      {/*
        The connected model failed and the documents answered instead. Worth
        saying plainly: the answer above is sound, but it is narrower than the
        one the user was expecting, and the key probably needs attention.
      */}
      {message.degradedReason && (
        <p className="turn-notice">
          <strong>Answered from your documents only.</strong> The connected AI model
          could not be reached — {message.degradedReason}
        </p>
      )}

      {message.citations.length > 0 && (
        <ul className="turn-sources">
          {message.citations.map((citation) => (
            <li key={citation.chunk_id}>
              <button
                type="button"
                className={`source-link${
                  activeChunkId === citation.chunk_id ? ' source-link-active' : ''
                }`}
                onClick={() => onSelectCitation(citation)}
              >
                <span className="source-marker">{citation.marker}</span>
                <span className="source-name">{citation.filename}</span>
                <span className="source-page">p.{citation.page}</span>
              </button>
            </li>
          ))}
        </ul>
      )}

      {!message.streaming && !message.error && message.latencyMs !== null && (
        <p className="turn-meta">
          {/*
            Which mode produced the answer changes how much scrutiny it deserves,
            so it is stated per answer rather than only in the settings panel: a
            transcript can mix both if the user connects or disconnects a key
            mid-conversation.
          */}
          {message.answerMode !== null && (
            <span
              className={`answer-mode answer-mode--${
                message.answerMode === 'documents_only' ? 'documents' : 'llm'
              }`}
              title={
                message.answerMode === 'documents_only'
                  ? 'Every sentence was taken from your uploaded documents.'
                  : `Generated by ${message.model ?? 'the connected model'} from your documents. ` +
                    'Anything outside them is labelled in the answer.'
              }
            >
              {message.answerMode === 'documents_only' ? 'Documents only' : 'Documents + AI'}
            </span>
          )}
          {(message.latencyMs / 1000).toFixed(1)}s
          {message.completionTokens !== null && ` · ${message.completionTokens} tokens`}
          {` · ${message.citations.length} citation${message.citations.length === 1 ? '' : 's'}`}
          {message.sources.length > 0 && ` from ${message.sources.length} sources`}
        </p>
      )}
    </article>
  )
}
